name: Deploy Sphinx

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-sphinx
        pip install recommonmark
        pip install sphinx_rtd_theme

    - name: Build Sphinx docs
      run: |
        make html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.ACTION }}
        publish_dir: ./build/html

